### ISSUE TITLE
Конфликт

### ISSUE THREAD

**Issue by gerundv** [gerundv/hello-world#2]

**Comment by gerundv** [comment]
Февраль еще грозит снегами,
Но побледнел зимы портрет
И вот уж черными кругами
Стал под стволами белый снег
В туманной дымке контур тает
И ни звезды на небе нет
Все чаще слякоть под ногами,
Все раньше каждый день рассвет..

**Comment by Ivan5333** [comment]
Февраль еще грозит снегами,
Но побледнел зимы портрет
И вот уж черными кругами
Стал под стволами белый снег
Мда

**Comment by gerundv** [comment]
> Февраль еще грозит снегами,
> Но побледнел зимы портрет
> И вот уж черными кругами
> Стал под стволами белый снег
> Мда

**Comment by gerundv** [comment]
Февраль еще грозит снегами,
Но побледнел зимы портрет
И вот уж черными кругами
Стал под стволами белый снег
В туманной дымке контур тает
И ни звезды на небе нет
Все чаще слякоть под ногами,
Все раньше каждый день рассвет..
